require:
  - rubocop-rails

AllCops:
  EnabledByDefault: true
  Include:
    - 'app/**/*' # Include all files in the 'app' directory
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'